name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.29.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm run build

      - name: Deploy to Firebase
        run: pnpm firebase --project nick-white-cc --token "$FIREBASE_TOKEN" deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
